---
title: "Homework 4"
author: "Ong Jia Yue"
date: "2024-12-15"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
  results = 'hide',
  message = FALSE,
  warning = FALSE,
  fig.align = 'left')

library(spatstat)
library(spatstat.explore)
library(spatstat.geom)
library(sf)
library(ggplot2)
library(dplyr)
```

setwd("~/02. MUSA Year 1/MUSA 5000- Statistical And Data Mining Methods For Urban Data Analysis/MUSA5000-Statistical-and-Data-Mining-Homework4-5")

# Import data
```{r import data}

Philly<- st_read("./HW4/Philadelphia.shp")

Markets<-st_read("./HW4/Philadelphia_Farmers_Markets201302.shp")

Philly_Zip<-st_read("./HW4/Philadelphia_ZipCodes.shp")
```

# Point Pattern
```{r}
# Plot points and boundary
ggplot() +
  geom_sf(data = Philly, fill = "lightblue", color = "black") +
  geom_sf(data = Markets, color = "red", size = 2) +
  theme_minimal()
```

# Following Eugene's Code
```{r Eugene's Code}
# Boundary
BoundaryPolygonsOW <- as.owin(Philly)

#Plotting the boundary window
plot(BoundaryPolygonsOW, main=NULL)
title(main = "Point Pattern Analysis")

# Coordinates
coords<- data.frame(st_coordinates(Markets))
# Check for duplicated values
cbind(coords,duplicated(coords$X,coords$Y))
coords2<-coords[!duplicated(coords), ]

# Points
pp2 <- ppp(coords2$X, coords2$Y, window=BoundaryPolygonsOW)
plot(pp2,add=T)
```

# Nearest Neighbor Analysis
```{r Nearest Neighbor}
# dev.off() 
#Computes the distance from each point to its nearest neighbour in a point pattern.
nnd <- nndist.ppp(pp2)
#Using the formulas on the slides, we calculate Mean Observed Distance,
#Mean Expected Distance and the Standard Error.
MeanObsDist <- mean(nnd)
#The area.owin command calculates the area of the study area that you use. Here it's the minimum enclosing rectangle, but it doesn't have to be - it could be any shapefile you import from ArcGIS (or generate in R) that corresponds to the study area.
MeanExpDist <- 0.5 / sqrt(nrow(coords2) / area.owin(BoundaryPolygonsOW))
SE <- 0.26136 / sqrt(nrow(coords2)*nrow(coords2) / area.owin(BoundaryPolygonsOW))

#Calculating the z-score
zscore <- (MeanObsDist - MeanExpDist)/SE

#Statistical test
#Here, if the z score is positive, we do an upper-tailed test and if the z score is negative we do a lower-tailed test to come up with the p-value.
pval<-ifelse(zscore > 0, 1 - pnorm(zscore), pnorm(zscore))

#Calculating the NNI
NNI <- MeanObsDist / MeanExpDist
pval
NNI
```

# K-Function Analysis
```{r K-Function Analysis}
khat <-Kest(pp2, rmax=25000) #,correction="Ripley")
#Plots Ripley's K function calculated with Ripley's isotropic edge correction, with line width 2, axis labels, and a main title.
plot(khat$r,khat$iso,xlab="r", ylab="Ripley's K",
     main="Ripley's Estimated K-Function",
     cex.lab=1.6,cex.axis=1.5,cex.main=1.5,lty=1,lwd=2)

# Overlays the theoretical K-function under CSR with a dashed (lty=8) line.
lines(khat$r,khat$theo,lty=8, lwd=2) 

#Code to compute the Ripley's Simulation Confidence Envelopes
#Computes confidence envelopes using n=199 simulations. Here, nrank=1 means we're looking at the lowest and highest values of the simulated envelopes. Here, alpha = 2 * nrank/(1 + nsim) = 2*1/200 = 0.01
#spatstat::envelope is to specify that the envelope command is in the spatstat library and not the boot library.

Kenv <- spatstat.explore::envelope(pp2,fun="Kest",rmax=25000, nsim=99, nrank=1) 

# Plots Ripley's K function with 99% simulation # envelopes, axis labels, and a title.

plot(Kenv,xlab="r",ylab="Khat(r)", cex.lab=1.6,cex.axis=1.5,main= 
       "Ripley's Khat with Confidence Envelopes",cex.main=1.5,lwd=2)
```





# L-Function Analysis
```{r L-Function Analysis}
#Computes Ripley's L* for each sample event
lhat <- Lest(pp2, rmax=75000) 
#Plots Ripley's L function calculated with line width 2, Ripley's isotropic edge correction, with axis labels, and a main title.
plot(lhat$r,lhat$iso-lhat$r, xlab="r",ylab="Ripley's L",cex.lab=1.6,  
     cex.axis=1.5,cex.main=1.5,lty=1,lwd=2, main="Ripley's Estimated L-Function") 
#Overlays the theoretical L-function under CSR with a dashed (lty=8) line.
lines(lhat$r,lhat$theo-lhat$r,lty=8,lwd=2) 

#Code to compute the Ripley's Simulation Confidence Envelopes
#Computes confidence envelopes using n=199 simulations. Here, nrank=1 means we're looking at the lowest and highest values of the simulated envelopes. Here, alpha = 2 * nrank/(1 + nsim) = 2*1/200 = 0.01
Lenv <- spatstat.explore::envelope(pp2,fun="Lest", rmax=25000, nsim=99,nrank=1)

# Plots Ripley's L function with 99% simulation envelopes, axis labels, and a title.
plot(Lenv,xlab="r",ylab="Lhat(r)", cex.lab=1.6,cex.axis=1.5,
     main= "Ripley's Lhat with Confidence Envelopes",cex.main=1.5,lwd=2,legend=F)

#A better way to view this is to rotate this plot 45 degrees clockwise.
#Gives the Ripley's data frame a new name L2.
L2 <- Lenv 
#Now we will subtract the distance r from the R-defined Ripley's L's
#(This will be done for the observed L, theoretical L, lower and uper envelopes)
L2$obs <- L2$obs-L2$r
L2$theo <- L2$theo-L2$r
L2$lo <- L2$lo-L2$r
L2$hi <- L2$hi-L2$r

# Plots Ripley's L function with 99% simulation envelopes, axis labels, and a title.
plot(L2,xlab="r",ylab="Lhat(r)", cex.lab=1.6,cex.axis=1.5,
     main= "Ripley's Lhat with Confidence Envelopes",cex.main=1.5,lwd=2,legend=F)
```


# Map of the farmers markets overlaid on a map of median household income at the zip code level 
```{r Map}
ggplot() +
  geom_sf(data = Philly_Zip, aes(fill = MedIncome), color = "black") +
  geom_sf(data = Markets, color = "blue", size = 2) +
  scale_fill_viridis_c(option = "cividis")+
  theme_minimal()
```



